export const CarConstants = {
  colors: [
    {
      value: "red",
      arValue: "احمر",
    },
    {
      value: "black",
      arValue: "اسود",
    },
    {
      value: "white",
      arValue: "ابيض",
    },
    {
      value: "silver",
      arValue: "فضي",
    },
    {
      value: "darkblue",
      arValue: "ازرق",
    },
  ],
  bodyStyle: [
    {
      value: "style1",
      arValue: "شكل 1",
    },
    {
      value: "style2",
      arValue: "شكل 2",
    },
    {
      value: "style3",
      arValue: "شكل 3",
    },
  ],
  brands: [
    { value: "Toyota", arValue: "تويوتا" },
    { value: "Honda", arValue: "هوندا" },
    { value: "Ford", arValue: "فورد" },
    { value: "Chevrolet", arValue: "شيفروليه" },
    { value: "Nissan", arValue: "نيسان" },
    { value: "BMW", arValue: "بي إم دبليو" },
    { value: "Mercedes-Benz", arValue: "مرسيدس بنز" },
    { value: "Audi", arValue: "أودي" },
    { value: "Lexus", arValue: "لكزس" },
    { value: "Hyundai", arValue: "هيونداي" },
  ],
  models: [
    { value: "Corolla", arValue: "كورولا" },
    { value: "Civic", arValue: "سيفيك" },
    { value: "Mustang", arValue: "موستانج" },
    { value: "Equinox", arValue: "ايكوينوكس" },
    { value: "Altima", arValue: "التيما" },
    { value: "3 Series", arValue: "السلسلة 3" },
    { value: "Toyota Camry", arValue: "تويوتا كامري" },
    { value: "Honda Accord", arValue: "هوندا أكورد" },
    { value: "Ford Mustang", arValue: "فورد موستانج" },
    { value: "Chevrolet Malibu", arValue: "شيفروليه ماليبو" },
    { value: "Nissan Altima", arValue: "نيسان التيما" },
    { value: "BMW 3 Series", arValue: "بي إم دبليو الفئة 3" },
    { value: "Mercedes-Benz C-Class", arValue: "مرسيدس بنز الفئة C" },
    { value: "Audi A4", arValue: "أودي A4" },
    { value: "Lexus ES", arValue: "لكزس ES" },
    { value: "Hyundai Sonata", arValue: "هيونداي سوناتا" },
    { value: "Model 3", arValue: "موديل 3" },
    { value: "Q5", arValue: "كيو 5" },
    { value: "E-Class", arValue: "الفئة E" },
    { value: "Tahoe", arValue: "تاهو" },
    { value: "Outback", arValue: "آوتباك" },
    { value: "RX 350", arValue: "آر إكس 350" },
    { value: "F-150", arValue: "إف-150" },
    { value: "X5", arValue: "إكس5" },
    { value: "CR-V", arValue: "سي آر ڤي" },
    { value: "RAV4", arValue: "راف 4" },
    { value: "Model Y", arValue: "موديل واي" },
    { value: "Silverado", arValue: "سيلفيرادو" },
    { value: "Escape", arValue: "إسكيب" },
    { value: "GLE 350", arValue: "جي.إل.إي 350" },
    { value: "4 Series", arValue: "الفئة 4" },
    { value: "Accord", arValue: "أكورد" },
    { value: "Grand Cherokee", arValue: "جراند شيروكي" },
    { value: "Highlander", arValue: "هايلاندر" },
    { value: "Explorer", arValue: "إكسبلورر" },
    { value: "Camaro", arValue: "كامارو" },
    { value: "A4", arValue: "أيه 4" },
    { value: "Forester", arValue: "فورستر" },
    { value: "Fusion", arValue: "فيوجن" },
    { value: "Telluride", arValue: "تيلورايد" },
  ],
  transmissionTypes: [
    {
      value: "automatic",
      arValue: "أوتوماتيك",
    },
    {
      value: "manual",
      arValue: "يدوي",
    },
    {
      value: "continuously-variable",
      arValue: "متغيرة السرعة",
    },
    { value: "Electric", arValue: "كهربائي" },

    {
      value: "semi-automatic",
      arValue: "شبه أوتوماتيك",
    },
    {
      value: "dual-clutch",
      arValue: "دبل كلاتش",
    },
    { value: "CVT", arValue: "متغيرة السرعة" },
  ],
};
