export const CarConstants = {
  colors: [
    {
      value: "red",
      arValue: "احمر",
    },
    {
      value: "black",
      arValue: "اسود",
    },
    {
      value: "white",
      arValue: "ابيض",
    },
    {
      value: "silver",
      arValue: "فضي",
    },
    {
      value: "darkblue",
      arValue: "ازرق",
    },
  ],
  bodyStyle: [
    {
      value: "style1",
      arValue: "شكل 1",
    },
    {
      value: "style2",
      arValue: "شكل 2",
    },
    {
      value: "style3",
      arValue: "شكل 3",
    },
  ],
  models: [
    { value: "Corolla", arValue: "كورولا" },
    { value: "Civic", arValue: "سيفيك" },
    { value: "Mustang", arValue: "موستانج" },
    { value: "Equinox", arValue: "ايكوينوكس" },
    { value: "Altima", arValue: "التيما" },
    { value: "3 Series", arValue: "السلسلة 3" },
    { value: "Model 3", arValue: "موديل 3" },
    { value: "Q5", arValue: "كيو 5" },
    { value: "E-Class", arValue: "الفئة E" },
    { value: "Tahoe", arValue: "تاهو" },
    { value: "Outback", arValue: "آوتباك" },
    { value: "RX 350", arValue: "آر إكس 350" },
    { value: "F-150", arValue: "إف-150" },
    { value: "X5", arValue: "إكس5" },
    { value: "CR-V", arValue: "سي آر ڤي" },
    { value: "RAV4", arValue: "راف 4" },
    { value: "Model Y", arValue: "موديل واي" },
    { value: "Silverado", arValue: "سيلفيرادو" },
    { value: "Escape", arValue: "إسكيب" },
    { value: "GLE 350", arValue: "جي.إل.إي 350" },
    { value: "4 Series", arValue: "الفئة 4" },
    { value: "Accord", arValue: "أكورد" },
    { value: "Grand Cherokee", arValue: "جراند شيروكي" },
    { value: "Highlander", arValue: "هايلاندر" },
    { value: "Explorer", arValue: "إكسبلورر" },
    { value: "Camaro", arValue: "كامارو" },
    { value: "A4", arValue: "أيه 4" },
    { value: "Forester", arValue: "فورستر" },
    { value: "Fusion", arValue: "فيوجن" },
    { value: "Telluride", arValue: "تيلورايد" },
  ],
  transmissions: [
    { value: "Automatic", arValue: "أوتوماتيك" },
    { value: "CVT", arValue: "متغيرة السرعة" },
    { value: "Manual", arValue: "يدوي" },
    { value: "Electric", arValue: "كهربائي" },
  ],
};
