export const CarConstants = {
  colors: [
    {
      value: "red",
      arValue: "احمر",
    },
    {
      value: "black",
      arValue: "اسود",
    },
    {
      value: "white",
      arValue: "ابيض",
    },
    {
      value: "silver",
      arValue: "فضي",
    },
    {
      value: "darkblue",
      arValue: "ازرق",
    },
  ],
  bodyStyle: [
    {
      value: "style1",
      arValue: "شكل 1",
    },
    {
      value: "style2",
      arValue: "شكل 2",
    },
    {
      value: "style3",
      arValue: "شكل 3",
    },
  ],
  brands: [
    { value: "Toyota", arValue: "تويوتا" },
    { value: "Honda", arValue: "هوندا" },
    { value: "Ford", arValue: "فورد" },
    { value: "Chevrolet", arValue: "شيفروليه" },
    { value: "Nissan", arValue: "نيسان" },
    { value: "BMW", arValue: "بي إم دبليو" },
    { value: "Mercedes-Benz", arValue: "مرسيدس بنز" },
    { value: "Audi", arValue: "أودي" },
    { value: "Lexus", arValue: "لكزس" },
    { value: "Hyundai", arValue: "هيونداي" },
  ],
  models: [
    { value: "Corolla", arValue: "كورولا" },
    { value: "Civic", arValue: "سيفيك" },
    { value: "Mustang", arValue: "موستانج" },
    { value: "Equinox", arValue: "ايكوينوكس" },
    { value: "Altima", arValue: "التيما" },
    { value: "3 Series", arValue: "السلسلة 3" },
    { value: "Toyota Camry", arValue: "تويوتا كامري" },
    { value: "Honda Accord", arValue: "هوندا أكورد" },
    { value: "Ford Mustang", arValue: "فورد موستانج" },
    { value: "Chevrolet Malibu", arValue: "شيفروليه ماليبو" },
    { value: "Nissan Altima", arValue: "نيسان التيما" },
    { value: "BMW 3 Series", arValue: "بي إم دبليو الفئة 3" },
    { value: "Mercedes-Benz C-Class", arValue: "مرسيدس بنز الفئة C" },
    { value: "Audi A4", arValue: "أودي A4" },
    { value: "Lexus ES", arValue: "لكزس ES" },
    { value: "Hyundai Sonata", arValue: "هيونداي سوناتا" },
    { value: "Model 3", arValue: "موديل 3" },
    { value: "Q5", arValue: "كيو 5" },
    { value: "E-Class", arValue: "الفئة E" },
    { value: "Tahoe", arValue: "تاهو" },
    { value: "Outback", arValue: "آوتباك" },
    { value: "RX 350", arValue: "آر إكس 350" },
    { value: "F-150", arValue: "إف-150" },
    { value: "X5", arValue: "إكس5" },
    { value: "CR-V", arValue: "سي آر ڤي" },
    { value: "RAV4", arValue: "راف 4" },
    { value: "Model Y", arValue: "موديل واي" },
    { value: "Silverado", arValue: "سيلفيرادو" },
    { value: "Escape", arValue: "إسكيب" },
    { value: "GLE 350", arValue: "جي.إل.إي 350" },
    { value: "4 Series", arValue: "الفئة 4" },
    { value: "Accord", arValue: "أكورد" },
    { value: "Grand Cherokee", arValue: "جراند شيروكي" },
    { value: "Highlander", arValue: "هايلاندر" },
    { value: "Explorer", arValue: "إكسبلورر" },
    { value: "Camaro", arValue: "كامارو" },
    { value: "A4", arValue: "أيه 4" },
    { value: "Forester", arValue: "فورستر" },
    { value: "Fusion", arValue: "فيوجن" },
    { value: "Telluride", arValue: "تيلورايد" },
  ],
  transmissionTypes: [
    {
      arValue: "أوتوماتيك",
    },
    {
      value: "manual",
      arValue: "يدوي",
    },
    {
      value: "continuously-variable",
      arValue: "متغيرة السرعة",
    },
    { value: "Electric", arValue: "كهربائي" },

    {
      value: "semi-automatic",
      arValue: "شبه أوتوماتيك",
    },
    {
      value: "dual-clutch",
      arValue: "دبل كلاتش",
    },
    { value: "CVT", arValue: "متغيرة السرعة" },
  ],
  features: [
    "Air Conditioning",
    "Power Steering",
    "Power Windows",
    "Power Door Locks",
    "Cruise Control",
    "AM/FM Radio",
    "CD Player",
    "MP3 Player",
    "Bluetooth Connectivity",
    "Navigation System",
    "Leather Seats",
    "Heated Seats",
    "Ventilated Seats",
    "Sunroof/Moonroof",
    "Backup Camera",
    "Parking Sensors",
    "Blind Spot Monitoring",
    "Lane Departure Warning",
    "Collision Avoidance System",
    "ABS (Anti-lock Braking System)",
    "Traction Control",
    "Stability Control",
    "Airbags",
    "Tire Pressure Monitoring",
    "Keyless Entry",
    "Push Button Start",
    "Remote Start",
    "Four-Wheel Drive (4WD)",
    "All-Wheel Drive (AWD)",
    "Fuel Efficiency (e.g., Hybrid, Electric)",
    "Towing Package",
    "Roof Rails",
    "Fold-Flat Seats",
    "Third-Row Seating",
    "Cargo Space",
    "Adjustable Steering Wheel",
    "Memory Seats",
    "Smartphone Integration",
    "Wi-Fi Hotspot",
    "Wireless Phone Charging",
  ],
};

export const Brands = [
  "Toyota - تويوتا",
  "Honda - هوندا",
  "Ford - فورد",
  "Chevrolet - شيفروليه",
  "Nissan - نيسان",
  "BMW - بي إم دبليو",
  "Mercedes-Benz - مرسيدس بنز",
  "Audi - أودي",
  "Lexus - لكزس",
  "Hyundai - هيونداي",
];
export const Models = [
  "Corolla - كورولا",
  "Civic - سيفيك",
  "Mustang - موستانج",
  "Equinox - ايكوينوكس",
  "Altima - التيما",
  "3 Series - السلسلة 3",
  "Toyota Camry - تويوتا كامري",
  "Honda Accord - هوندا أكورد",
  "Ford Mustang - فورد موستانج",
  "Chevrolet Malibu - شيفروليه ماليبو",
  "Nissan Altima - نيسان التيما",
  "BMW 3 Series - بي إم دبليو الفئة 3",
  "Mercedes-Benz C-Class - مرسيدس بنز الفئة C",
  "Audi A4 - أودي A4",
  "Lexus ES - لكزس ES",
  "Hyundai Sonata - هيونداي سوناتا",
  "Model 3 - موديل 3",
  "Q5 - كيو 5",
  "E-Class - الفئة E",
  "Tahoe - تاهو",
  "Outback - آوتباك",
  "RX 350 - آر إكس 350",
  "F-150 - إف-150",
  "X5 - إكس5",
  "CR-V - سي آر ڤي",
  "RAV4 - راف 4",
  "Model Y - موديل واي",
  "Silverado - سيلفيرادو",
  "Escape - إسكيب",
  "GLE 350 - جي.إل.إي 350",
  "4 Series - الفئة 4",
  "Accord - أكورد",
  "Grand Cherokee - جراند شيروكي",
  "Highlander - هايلاندر",
  "Explorer - إكسبلورر",
  "Camaro - كامارو",
  "A4 - أيه 4",
  "Forester - فورستر",
  "Fusion - فيوجن",
  "Telluride - تيلورايد",
];

export const Transmission = [
  "أوتوماتيك",
  "manual - يدوي",
  "continuously-variable - متغيرة السرعة",
  "Electric - كهربائي",
  "semi-automatic - شبه أوتوماتيك",
  "dual-clutch - دبل كلاتش",
  "CVT - متغيرة السرعة",
];
